#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/app/config.yml" ]]; then
    echo "Installing default \"config.yml\"..."
    cp /app/config.yml "${CONFIG_DIR}/app/config.yml"
    chown hotio:hotio "${CONFIG_DIR}/app/config.yml"
fi

if [[ ! -f "${CONFIG_DIR}/app/plex.token" ]] && [[ -n ${PLEX_LOGIN} ]] && [[ -n ${PLEX_PASSWORD} ]]; then
    echo "Trying to get a Plex token for Autoscan..."
    curl -fsSL -u "${PLEX_LOGIN}":"${PLEX_PASSWORD}" 'https://plex.tv/users/sign_in.json' -X POST -H 'X-Plex-Client-Identifier: '"$(uuidgen)" -H 'X-Plex-Product: Autoscan' -H 'X-Plex-Provides: controller' -H 'X-Plex-Device: '"$(uname -s) $(uname -r)" | jq . \
        > "${CONFIG_DIR}/app/plex.token" && chown hotio:hotio "${CONFIG_DIR}/app/plex.token"

    token="$(jq -r .[].authentication_token "${CONFIG_DIR}/app/plex.token")"
    if [[ -n ${token} ]] && [[ ${token} != null ]]; then
        echo "Your Plex token is: ${token}, you can use this in your config.yml."
    else
        echo "Something went wrong trying to get a token!"
    fi
fi
